
version: '3.9'

services:
  ts-node-server:
    build:
      context: ../
      dockerfile: docker_product/product.Dockerfile
      # target: base
    volumes:
      - ./src:/usr/src/app/src
    #   - ./prisma:/usr/src/app/prisma
    #   - ./other:/usr/src/app/other
    container_name: ts-node-server
    working_dir: /usr/src/app/
    ports:
      - '4000:4000'
      - '4443:4443'
    networks:
      - backend
    command: npm start
    env_file:
      - ../.env    
    environment:
      - HOSTNAME=${HOSTNAME}
      - FRONT_END_HOST=${FRONT_END_HOST}
    depends_on: 
      - db
  db:
    container_name: db
    build: 
      context: ..
      dockerfile: mysql.Dockerfile
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - ../.env   
    networks:
      - backend
    # volumes:
    #   - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - /data/redis-data:/data  
      - ./other:/etc/redis
    networks:
      - backend         
  nginx: 
    build: 
      context: ..
      dockerfile: docker_product/nginx.Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./templates:/etc/nginx/templates
      - ./src/certreq:/etc/nginx/ssl
      - ../build/web:/usr/share/nginx/html
    networks:
      - backend     
    # volumes:
    #   - ./app/build/web:/usr/share/nginx/html
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend


networks:
  backend:
