version: "3.9"
   
services:
  codegen:
    image: "rust:latest"
    container_name: ${GEN_TYPE}_codegen
    working_dir: /codegen
    stdin_open: true
    tty: true    
    # command: cargo run
    volumes:
      - ${GEN_OUTPUT_DIR}/${GEN_OUTPUT_DIR_NAME}:/${GEN_OUTPUT_DIR_NAME}
      # - ../server:/server
      - .:/codegen
    environment:
      - GEN_TYPE=${GEN_TYPE} 

