version: '3.9'

services:
  ts-node-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./prisma:/home/node/app/prisma
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-server
    expose:
      - '4000'
    ports:
      - '4000:4000'
    networks:
      - backend
    command: npm run dev
    env_file:
      - .env    
    depends_on: 
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    networks:
      - backend
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - /data/redis-data:/data  
      - ./redis.conf:/etc/redis/redis.conf 
    networks:
      - backend         
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
